// auto-generated by sequelize-cli

import { fs } from 'fs'
import path from 'path'
import { Sequelize } from 'sequelize-typescript'
const basename = path.basename(__filename)
import { database as config } from '../../config'

const db = {
  sequelize: null,
  authenticate: null
}

const sequelize = new Sequelize({ models: [__dirname + '/src/models/*.ts'], ...config })

fs
  .readdirSync(__dirname)
  .filter(file => {
    return (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js')
  })
  .forEach(file => {
    const model = require(path.join(__dirname, file))(sequelize, Sequelize.DataTypes)
    db[model.name] = model
  })

Object.keys(db).forEach(modelName => {
  if (db[modelName].associate) {
    db[modelName].associate(db)
  }
})

db.sequelize = sequelize

db.authenticate = sequelize.authenticate.bind(sequelize)

export default  { db }
